/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alumnotd
 */
public class Ahorcado extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ahorcado.class.getName());

	/**
	 * Creates new form Ahorcado
	 */
	public Ahorcado() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelGeneral = new javax.swing.JPanel();
                jButtonComenzar = new javax.swing.JButton();
                jButtonResolver = new javax.swing.JButton();
                jPanelPalabra = new javax.swing.JPanel();
                jPanelMuneco = new javax.swing.JPanel();
                jLabelCabeza = new javax.swing.JLabel();
                jLabelTorso = new javax.swing.JLabel();
                jLabelPiernaDerecha = new javax.swing.JLabel();
                jLabelPiernaIzquierda = new javax.swing.JLabel();
                jLabelBrazoDerecho = new javax.swing.JLabel();
                jLabelBrazoIzquierdo = new javax.swing.JLabel();
                jRadioArbol = new javax.swing.JRadioButton();
                jLabelArbol = new javax.swing.JLabel();
                jLabelArbol1 = new javax.swing.JLabel();
                jLabelArbol2 = new javax.swing.JLabel();
                jLabelLetras = new javax.swing.JLabel();
                jPanelTeclado = new javax.swing.JPanel();
                jButtonA = new javax.swing.JButton();
                jButtonB = new javax.swing.JButton();
                jButtonC = new javax.swing.JButton();
                jButtonD = new javax.swing.JButton();
                jButtonE = new javax.swing.JButton();
                jButtonF = new javax.swing.JButton();
                jButtonG = new javax.swing.JButton();
                jButtonH = new javax.swing.JButton();
                jButtonI = new javax.swing.JButton();
                jButtonJ = new javax.swing.JButton();
                jButtonK = new javax.swing.JButton();
                jButtonL = new javax.swing.JButton();
                jButtonM = new javax.swing.JButton();
                jButtonN = new javax.swing.JButton();
                jButtonÑ = new javax.swing.JButton();
                jButtonO = new javax.swing.JButton();
                jButtonP = new javax.swing.JButton();
                jButtonQ = new javax.swing.JButton();
                jButtonR = new javax.swing.JButton();
                jButtonS = new javax.swing.JButton();
                jButtonT = new javax.swing.JButton();
                jButtonU = new javax.swing.JButton();
                jButtonV = new javax.swing.JButton();
                jButtonW = new javax.swing.JButton();
                jButtonX = new javax.swing.JButton();
                jButtonY = new javax.swing.JButton();
                jButtonZ = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jButtonComenzar.setText("Comenzar/Reset");
                jButtonComenzar.addActionListener(this::jButtonComenzarActionPerformed);

                jButtonResolver.setText("Resolver");
                jButtonResolver.addActionListener(this::jButtonResolverActionPerformed);

                javax.swing.GroupLayout jPanelPalabraLayout = new javax.swing.GroupLayout(jPanelPalabra);
                jPanelPalabra.setLayout(jPanelPalabraLayout);
                jPanelPalabraLayout.setHorizontalGroup(
                        jPanelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 312, Short.MAX_VALUE)
                );
                jPanelPalabraLayout.setVerticalGroup(
                        jPanelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
                );

                jLabelCabeza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelCabeza.setText("O");

                jLabelTorso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelTorso.setText("|");

                jLabelPiernaDerecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelPiernaDerecha.setText("\\");

                        jLabelPiernaIzquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabelPiernaIzquierda.setText("/");

                        jLabelBrazoDerecho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabelBrazoDerecho.setText("\\");

                                jLabelBrazoIzquierdo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                jLabelBrazoIzquierdo.setText("/");

                                jRadioArbol.setText("-----|");
                                jRadioArbol.addActionListener(this::jRadioArbolActionPerformed);

                                jLabelArbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                jLabelArbol.setText("|");

                                jLabelArbol1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                jLabelArbol1.setText("|");

                                jLabelArbol2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                jLabelArbol2.setText("|");

                                javax.swing.GroupLayout jPanelMunecoLayout = new javax.swing.GroupLayout(jPanelMuneco);
                                jPanelMuneco.setLayout(jPanelMunecoLayout);
                                jPanelMunecoLayout.setHorizontalGroup(
                                        jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelMunecoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelMunecoLayout.createSequentialGroup()
                                                                .addGroup(jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabelArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabelArbol1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabelArbol2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(8, 8, 8)
                                                                .addGroup(jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanelMunecoLayout.createSequentialGroup()
                                                                                .addGroup(jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabelCabeza)
                                                                                        .addGroup(jPanelMunecoLayout.createSequentialGroup()
                                                                                                .addComponent(jLabelBrazoIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabelTorso, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jLabelBrazoDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE))
                                                                        .addGroup(jPanelMunecoLayout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(jLabelPiernaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jLabelPiernaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(jRadioArbol))
                                                .addContainerGap())
                                );
                                jPanelMunecoLayout.setVerticalGroup(
                                        jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelMunecoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jRadioArbol)
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelCabeza)
                                                        .addComponent(jLabelArbol))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelTorso)
                                                        .addComponent(jLabelBrazoDerecho)
                                                        .addComponent(jLabelBrazoIzquierdo)
                                                        .addComponent(jLabelArbol1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelMunecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelPiernaDerecha)
                                                        .addComponent(jLabelPiernaIzquierda)
                                                        .addComponent(jLabelArbol2))
                                                .addContainerGap(37, Short.MAX_VALUE))
                                );

                                jLabelLetras.setText("Letras elegidas: ");

                                jButtonA.setText("A");
                                jButtonA.addActionListener(this::jButtonAActionPerformed);

                                jButtonB.setText("B");
                                jButtonB.addActionListener(this::jButtonBActionPerformed);

                                jButtonC.setText("C");
                                jButtonC.addActionListener(this::jButtonCActionPerformed);

                                jButtonD.setText("D");
                                jButtonD.addActionListener(this::jButtonDActionPerformed);

                                jButtonE.setText("E");
                                jButtonE.addActionListener(this::jButtonEActionPerformed);

                                jButtonF.setText("F");
                                jButtonF.addActionListener(this::jButtonFActionPerformed);

                                jButtonG.setText("G");
                                jButtonG.addActionListener(this::jButtonGActionPerformed);

                                jButtonH.setText("H");
                                jButtonH.addActionListener(this::jButtonHActionPerformed);

                                jButtonI.setText("I");
                                jButtonI.addActionListener(this::jButtonIActionPerformed);

                                jButtonJ.setText("J");
                                jButtonJ.addActionListener(this::jButtonJActionPerformed);

                                jButtonK.setText("K");
                                jButtonK.addActionListener(this::jButtonKActionPerformed);

                                jButtonL.setText("L");
                                jButtonL.addActionListener(this::jButtonLActionPerformed);

                                jButtonM.setText("M");
                                jButtonM.addActionListener(this::jButtonMActionPerformed);

                                jButtonN.setText("N");
                                jButtonN.addActionListener(this::jButtonNActionPerformed);

                                jButtonÑ.setText("Ñ");
                                jButtonÑ.addActionListener(this::jButtonÑActionPerformed);

                                jButtonO.setText("O");
                                jButtonO.addActionListener(this::jButtonOActionPerformed);

                                jButtonP.setText("P");
                                jButtonP.addActionListener(this::jButtonPActionPerformed);

                                jButtonQ.setText("Q");
                                jButtonQ.addActionListener(this::jButtonQActionPerformed);

                                jButtonR.setText("R");
                                jButtonR.addActionListener(this::jButtonRActionPerformed);

                                jButtonS.setText("S");
                                jButtonS.addActionListener(this::jButtonSActionPerformed);

                                jButtonT.setText("T");
                                jButtonT.addActionListener(this::jButtonTActionPerformed);

                                jButtonU.setText("U");
                                jButtonU.addActionListener(this::jButtonUActionPerformed);

                                jButtonV.setText("V");
                                jButtonV.addActionListener(this::jButtonVActionPerformed);

                                jButtonW.setText("W");
                                jButtonW.addActionListener(this::jButtonWActionPerformed);

                                jButtonX.setText("X");
                                jButtonX.addActionListener(this::jButtonXActionPerformed);

                                jButtonY.setText("Y");
                                jButtonY.addActionListener(this::jButtonYActionPerformed);

                                jButtonZ.setText("Z");
                                jButtonZ.addActionListener(this::jButtonZActionPerformed);

                                javax.swing.GroupLayout jPanelTecladoLayout = new javax.swing.GroupLayout(jPanelTeclado);
                                jPanelTeclado.setLayout(jPanelTecladoLayout);
                                jPanelTecladoLayout.setHorizontalGroup(
                                        jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTecladoLayout.createSequentialGroup()
                                                .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelTecladoLayout.createSequentialGroup()
                                                                .addGap(50, 50, 50)
                                                                .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanelTecladoLayout.createSequentialGroup()
                                                                                .addGap(44, 44, 44)
                                                                                .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanelTecladoLayout.createSequentialGroup()
                                                                                .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanelTecladoLayout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(64, Short.MAX_VALUE))
                                );
                                jPanelTecladoLayout.setVerticalGroup(
                                        jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTecladoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                );

                                javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
                                jPanelGeneral.setLayout(jPanelGeneralLayout);
                                jPanelGeneralLayout.setHorizontalGroup(
                                        jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                                .addComponent(jButtonComenzar)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                                                .addComponent(jPanelMuneco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                                                                .addComponent(jPanelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButtonResolver))
                                                                        .addComponent(jLabelLetras)))
                                                        .addComponent(jPanelTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())
                                );
                                jPanelGeneralLayout.setVerticalGroup(
                                        jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jButtonResolver))
                                                        .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                                                .addComponent(jPanelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelLetras))
                                                        .addComponent(jPanelMuneco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(50, 50, 50)
                                                .addComponent(jPanelTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonComenzar)
                                                .addContainerGap())
                                );

                                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                                getContentPane().setLayout(layout);
                                layout.setHorizontalGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                );
                                layout.setVerticalGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                );

                                pack();
                        }// </editor-fold>//GEN-END:initComponents

        private void jButtonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarActionPerformed
                // TODO add your handling code here:
		AhorcadoJuego ahorcado = new AhorcadoJuego();
		ahorcado.reset();
		for (char letra : ahorcado.getPalabraSorteada().toCharArray())
		{
			
		}
		
        }//GEN-LAST:event_jButtonComenzarActionPerformed

        private void jButtonResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonResolverActionPerformed

        private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonAActionPerformed

        private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonBActionPerformed

        private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonCActionPerformed

        private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonDActionPerformed

        private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonEActionPerformed

        private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonFActionPerformed

        private void jButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonGActionPerformed

        private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonHActionPerformed

        private void jButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonIActionPerformed

        private void jButtonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonJActionPerformed

        private void jButtonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonKActionPerformed

        private void jButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonLActionPerformed

        private void jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonMActionPerformed

        private void jButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonNActionPerformed

        private void jButtonÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonÑActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonÑActionPerformed

        private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonOActionPerformed

        private void jButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonPActionPerformed

        private void jButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonQActionPerformed

        private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonRActionPerformed

        private void jButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonSActionPerformed

        private void jButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonTActionPerformed

        private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonUActionPerformed

        private void jButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonVActionPerformed

        private void jButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonWActionPerformed

        private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonXActionPerformed

        private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonYActionPerformed

        private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonZActionPerformed

        private void jRadioArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioArbolActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jRadioArbolActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new Ahorcado().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonA;
        private javax.swing.JButton jButtonB;
        private javax.swing.JButton jButtonC;
        private javax.swing.JButton jButtonComenzar;
        private javax.swing.JButton jButtonD;
        private javax.swing.JButton jButtonE;
        private javax.swing.JButton jButtonF;
        private javax.swing.JButton jButtonG;
        private javax.swing.JButton jButtonH;
        private javax.swing.JButton jButtonI;
        private javax.swing.JButton jButtonJ;
        private javax.swing.JButton jButtonK;
        private javax.swing.JButton jButtonL;
        private javax.swing.JButton jButtonM;
        private javax.swing.JButton jButtonN;
        private javax.swing.JButton jButtonO;
        private javax.swing.JButton jButtonP;
        private javax.swing.JButton jButtonQ;
        private javax.swing.JButton jButtonR;
        private javax.swing.JButton jButtonResolver;
        private javax.swing.JButton jButtonS;
        private javax.swing.JButton jButtonT;
        private javax.swing.JButton jButtonU;
        private javax.swing.JButton jButtonV;
        private javax.swing.JButton jButtonW;
        private javax.swing.JButton jButtonX;
        private javax.swing.JButton jButtonY;
        private javax.swing.JButton jButtonZ;
        private javax.swing.JButton jButtonÑ;
        private javax.swing.JLabel jLabelArbol;
        private javax.swing.JLabel jLabelArbol1;
        private javax.swing.JLabel jLabelArbol2;
        private javax.swing.JLabel jLabelBrazoDerecho;
        private javax.swing.JLabel jLabelBrazoIzquierdo;
        private javax.swing.JLabel jLabelCabeza;
        private javax.swing.JLabel jLabelLetras;
        private javax.swing.JLabel jLabelPiernaDerecha;
        private javax.swing.JLabel jLabelPiernaIzquierda;
        private javax.swing.JLabel jLabelTorso;
        private javax.swing.JPanel jPanelGeneral;
        private javax.swing.JPanel jPanelMuneco;
        private javax.swing.JPanel jPanelPalabra;
        private javax.swing.JPanel jPanelTeclado;
        private javax.swing.JRadioButton jRadioArbol;
        // End of variables declaration//GEN-END:variables
}
